name: CI-CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Exécuter les tests
        working-directory: src
        run: | 
          python -m pytest 
  deploy:
    runs-on: self-hosted
    needs: test   # Démarre seulement si les tests passent
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploiement avec Docker Compose
        run: |
          cd $GITHUB_WORKSPACE
          docker compose down || true
          docker compose build --no-cache
          docker compose up -d
          

